openapi: 3.1.0
info:
  title: literal
  version: 0.0.0
  description: Test definition for literal schemas.
paths:
  /headers:
    post:
      operationId: headers_send
      tags:
        - Headers
      parameters:
        - name: X-Endpoint-Version
          in: header
          required: true
          schema:
            type: string
            const: 02-12-2024
          examples:
            Example1:
              value: 02-12-2024
        - name: X-Async
          in: header
          required: true
          schema:
            type: boolean
            const: true
          examples:
            Example1:
              value: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendResponse'
              examples:
                Example1:
                  value:
                    message: The weather is sunny
                    status: 200
                    success: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  examples:
                    - What is the weather today
              required:
                - query
            examples:
              Example1:
                value:
                  query: What is the weather today
  /inlined:
    post:
      operationId: inlined_send
      tags:
        - Inlined
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendResponse'
              examples:
                Example1:
                  value:
                    message: The weather is sunny
                    status: 200
                    success: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                  const: You are a helpful assistant
                context:
                  type:
                    - string
                    - 'null'
                  const: You're super wise
                query:
                  type: string
                  examples:
                    - What is the weather today
                temperature:
                  type:
                    - number
                    - 'null'
                  format: double
                stream:
                  type: boolean
                  const: false
                aliasedContext:
                  $ref: '#/components/schemas/SomeAliasedLiteral'
                maybeContext:
                  anyOf:
                    - $ref: '#/components/schemas/SomeAliasedLiteral'
                    - type: 'null'
                objectWithLiteral:
                  $ref: '#/components/schemas/ATopLevelLiteral'
              required:
                - prompt
                - query
                - stream
                - aliasedContext
                - objectWithLiteral
            examples:
              Example1:
                value:
                  temperature: 10.1
                  prompt: You are a helpful assistant
                  context: You're super wise
                  aliasedContext: You're super wise
                  maybeContext: You're super wise
                  objectWithLiteral:
                    nestedLiteral:
                      myLiteral: How super cool
                  stream: false
                  query: What is the weather today
  /path/{id}:
    post:
      operationId: path_send
      tags:
        - Path
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            const: '123'
          examples:
            Example1:
              value: '123'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendResponse'
              examples:
                Example1:
                  value:
                    message: The weather is sunny
                    status: 200
                    success: true
  /query:
    post:
      operationId: query_send
      tags:
        - Query
      parameters:
        - name: prompt
          in: query
          required: true
          schema:
            type: string
            const: You are a helpful assistant
          examples:
            Example1:
              value: You are a helpful assistant
        - name: optional_prompt
          in: query
          required: false
          schema:
            type:
              - string
              - 'null'
            const: You are a helpful assistant
          examples:
            Example1:
              value: You are a helpful assistant
        - name: alias_prompt
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/AliasToPrompt'
          examples:
            Example1:
              value: You are a helpful assistant
        - name: alias_optional_prompt
          in: query
          required: false
          schema:
            anyOf:
              - $ref: '#/components/schemas/AliasToPrompt'
              - type: 'null'
          examples:
            Example1:
              value: You are a helpful assistant
        - name: query
          in: query
          required: true
          schema:
            type: string
          examples:
            Example1:
              value: What is the weather today
        - name: stream
          in: query
          required: true
          schema:
            type: boolean
            const: false
          examples:
            Example1:
              value: false
        - name: optional_stream
          in: query
          required: false
          schema:
            type:
              - boolean
              - 'null'
            const: false
          examples:
            Example1:
              value: false
        - name: alias_stream
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/AliasToStream'
          examples:
            Example1:
              value: false
        - name: alias_optional_stream
          in: query
          required: false
          schema:
            anyOf:
              - $ref: '#/components/schemas/AliasToStream'
              - type: 'null'
          examples:
            Example1:
              value: false
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendResponse'
              examples:
                Example1:
                  value:
                    message: The weather is sunny
                    status: 200
                    success: true
  /reference:
    post:
      operationId: reference_send
      tags:
        - Reference
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendResponse'
              examples:
                Example1:
                  value:
                    message: The weather is sunny
                    status: 200
                    success: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendRequest'
            examples:
              Example1:
                value:
                  prompt: You are a helpful assistant
                  stream: false
                  context: You're super wise
                  query: What is the weather today
                  containerObject:
                    nestedObjects:
                      - literal1: literal1
                        literal2: literal2
                        strProp: strProp
components:
  schemas:
    SendResponse:
      title: SendResponse
      type: object
      properties:
        message:
          type: string
          examples:
            - The weather is sunny
        status:
          type: integer
          examples:
            - 200
        success:
          type: boolean
          const: true
      required:
        - message
        - status
        - success
    SomeAliasedLiteral:
      title: SomeAliasedLiteral
      type: string
      const: You're super wise
    ATopLevelLiteral:
      title: ATopLevelLiteral
      type: object
      properties:
        nestedLiteral:
          $ref: '#/components/schemas/ANestedLiteral'
      required:
        - nestedLiteral
    ANestedLiteral:
      title: ANestedLiteral
      type: object
      properties:
        myLiteral:
          type: string
          const: How super cool
      required:
        - myLiteral
    DiscriminatedLiteral:
      title: DiscriminatedLiteral
      oneOf:
        - type: object
          properties:
            type:
              type: string
              const: customName
            value:
              type: string
          required:
            - type
        - type: object
          properties:
            type:
              type: string
              const: defaultName
            value:
              type: string
              const: Bob
          required:
            - type
        - type: object
          properties:
            type:
              type: string
              const: george
            value:
              type: boolean
          required:
            - type
        - type: object
          properties:
            type:
              type: string
              const: literalGeorge
            value:
              type: boolean
              const: true
          required:
            - type
    UndiscriminatedLiteral:
      title: UndiscriminatedLiteral
      oneOf:
        - type: string
        - type: string
          const: $ending
        - type: string
          const: >-
            10 non-alphanumeric string literals you're going to love & why
            (number 8 will surprise you)
        - type: boolean
          const: true
        - type: boolean
          const: false
        - type: boolean
    AliasToPrompt:
      title: AliasToPrompt
      type: string
      const: You are a helpful assistant
    AliasToStream:
      title: AliasToStream
      type: boolean
      const: false
    SendRequest:
      title: SendRequest
      type: object
      properties:
        prompt:
          type: string
          const: You are a helpful assistant
        query:
          type: string
          examples:
            - What is the weather today
        stream:
          type: boolean
          const: false
        ending:
          type: string
          const: $ending
        context:
          $ref: '#/components/schemas/SomeLiteral'
        maybeContext:
          anyOf:
            - $ref: '#/components/schemas/SomeLiteral'
            - type: 'null'
        containerObject:
          $ref: '#/components/schemas/ContainerObject'
      required:
        - prompt
        - query
        - stream
        - ending
        - context
        - containerObject
    ContainerObject:
      title: ContainerObject
      type: object
      properties:
        nestedObjects:
          type: array
          items:
            $ref: '#/components/schemas/NestedObjectWithLiterals'
      required:
        - nestedObjects
    NestedObjectWithLiterals:
      title: NestedObjectWithLiterals
      type: object
      properties:
        literal1:
          type: string
          const: literal1
        literal2:
          type: string
          const: literal2
        strProp:
          type: string
      required:
        - literal1
        - literal2
        - strProp
    SomeLiteral:
      title: SomeLiteral
      type: string
      const: You're super wise
  securitySchemes: {}
